import MixTape from './mix-tape';

const centurion: MixTape = {
  name: 'Gebroeders Scooter - EscalaTIEN',
  songFile: '/audio/gebroeders-scooter-escalatien.mp3',
  feed: [
    { timestamp: 10, type: 'horn', data: { counter: 0 } },
    { timestamp: 46.00, type: 'song', data: { artist: 'Vanessa Carlton', title: 'A Thousand Miles' } },
    { timestamp: 1,37.00, type: 'song', data: { artist: 'Snoop Dogg, Wiz Khalifa, Bruno Mars', title: 'Young Wild & Free' } },
    { timestamp: 1,58.00, type: 'song', data: { artist: '???', title: '???' } },
    { timestamp: 1,33.50, type: 'horn', data: { counter: 1 } },
    { timestamp: 2,34.00, type: 'song', data: { artist: 'Nelly & The Partysquad', title: 'Ride Wit Me & Non Stop' } },
    { timestamp: 3,32.00, type: 'song', data: { artist: 'Natasha Beddingfield', title: 'Unwritten' } },
    { timestamp: 3,51.00, type: 'horn', data: { counter: 2 } },
    { timestamp: 4,19.00, type: 'song', data: { artist: '???', title: '???' } },
    { timestamp: 4,41.50, type: 'song', data: { artist: '???', title: '???' } },
    { timestamp: 5,00.00, type: 'song', data: { artist: 'Smashmouth', title: 'All Star' } },
    { timestamp: 5,37.00, type: 'horn', data: { counter: 3 } },
    { timestamp: 5,55.50, type: 'song', data: { artist: '???', title: '???' } },
    { timestamp: 6,27.00, type: 'horn', data: { counter: 4 } },
    {
      timestamp: 6,29.00,
      type: 'song',
      data: {
        artist: 'Bizzey, Jozo, Kraantje Pappie',
        title: 'Traag',
      },
    },
    { timestamp: 7,08.00, type: 'song', data: { artist: 'Bizzey, Kraantje Pappie, Chivv, Yung Felix', title: 'JA!' } },
    { timestamp: 7,27.00, type: 'song', data: { artist: 'Bizzey, Kraantje Pappie, Jonna Fraser, Ramiks', title: 'DRUP' } },
    { timestamp: 7,46.50, type: 'song', data: { artist: '???', title: '???' } },
    { timestamp: 8,05.50, type: 'song', data: { artist: 'Kelly Rowland, Nelly', title: 'Dilemma' } },
    { timestamp: 8,25.00, type: 'song', data: { artist: 'Justin Bieber', title: 'Sorry' } },
    { timestamp: 8,43.80, type: 'horn', data: { counter: 5 } },
    { timestamp: 9,03.00, type: 'song', data: { artist: 'Bruno Mars', title: 'Drippin in Finesse' } },
    { timestamp: 9,21.50, type: 'song', data: { artist: '???', title: '???' } },
    { timestamp: 9,40.00, type: 'song', data: { artist: 'K3', title: '10.000 luchtballonnen' } },
    { timestamp: 10,31.00, type: 'horn', data: { counter: 6 } },
    {
      timestamp: 10,33.00,
      type: 'song',
      data: { artist: 'Scissor Sisters', title: "I don't feel like dancing" },
    },
    { timestamp: 11,36.00, type: 'song', data: { artist: 'Robbie Williams', title: 'Rock DJ' } },
    { timestamp: 11,52.30, type: 'horn', data: { counter: 7 } },
    { timestamp: 12,21.50, type: 'song', data: { artist: '???', title: '???' } },
    { timestamp: 12.39.00, type: 'horn', data: { counter: 8 } },
    { timestamp: 12,57.50, type: 'song', data: { artist: 'Rebecca Black', title: 'Friday' } },
    { timestamp: 13,12.00, type: 'horn', data: { counter: 9 } },
    { timestamp: 13,40.00, type: 'horn', data: { counter: 10 } },
    {
      timestamp: 13,40.00,
      type: 'song',
      data: {
        artist: '???',
        title: '???',
      },
    },
    {
      timestamp: 14,13.00,
      type: 'song',
      data: { artist: 'Vanilla Ice', title: 'Ice Ice Baby' },
    },
    {
      timestamp: 14,30.00,
      type: 'song',
      data: { artist: '???', title: '???' },
    },
    { timestamp: 15,01.00, type: 'horn', data: { counter: 11 } },
    { timestamp: 15,02.00, type: 'song', data: { artist: 'Kees Diks', title: 'Het barbecuelied' } },
    { timestamp: 15,49.10, type: 'horn', data: { counter: 12 } },
    { timestamp: 15,51.00, type: 'song', data: { artist: 'De Jeugd van Tegenwoordig', title: 'Get Spanish' } },
    { timestamp: 16,37.00, type: 'horn', data: { counter: 13 } },
    { timestamp: 16,38.00, type: 'song', data: { artist: 'Sjaak', title: 'Stap voor stap' } },
    { timestamp: 17,23.80, type: 'horn', data: { counter: 14 } },
    {
      timestamp: 17,25.00,
      type: 'song',
      data: { artist: 'Jairzinho, Sven Alias, BKO, Boef', title: 'Tempo' },
    },
    { timestamp: 17,43.00, type: 'song', data: { artist: '???', title: '???' } },
    {
      timestamp: 18.13.00,
      type: 'song',
      data: { artist: 'Discodip', title: "Meisjes met IJsjes" },
    },
    { timestamp: 18,57.50, type: 'horn', data: { counter: 15 } },
    { timestamp: 18,59.00, type: 'song', data: { artist: 'MEROL', title: 'LEKKER MET DE MEIDEN/MANNEN' } },
    { timestamp: 19,45.70, type: 'horn', data: { counter: 16 } },
    { timestamp: 19,46.00, type: 'song', data: { artist: 'Twenty 4 Seven', title: 'Slave To The Music' } },
    {
      timestamp: 20,16.00,
      type: 'song',
      data: { artist: 'David Hasselhoff', title: 'Looking for Freedom' },
    },
    { timestamp: 20,16.00, type: 'horn', data: { counter: 17 } },
    {
      timestamp: 20,46.00,
      type: 'song',
      data: { artist: 'Boney M.', title: 'Rivers of Babylon' },
    },
    { timestamp: 21,17.41, type: 'horn', data: { counter: 18 } },
    { timestamp: 21,17.00, type: 'song', data: { artist: 'Gwen Stefani, Akon', title: 'The Sweet Escape' } },
    { timestamp: 21,54.50, type: 'song', data: { artist: '???', title: '???' } },
    { timestamp: 22,06.72, type: 'horn', data: { counter: 19 } },
    { timestamp: 22,36.00, type: 'song', data: { artist: 'Jessie J', title: 'Domino' } },
    { timestamp: 23,06.30, type: 'horn', data: { counter: 20 } },
    { timestamp: 23,06.30, type: 'song', data: { artist: 'Katy Perry', title: 'Teenage Dream' } },
    { timestamp: 23,34.30, type: 'horn', data: { counter: 21 } },
    { timestamp: 23,36.00, type: 'song', data: { artist: 'Bon Jovi', title: 'Livin' on a Prayer' } },
    { timestamp: 23,55.40, type: 'horn', data: { counter: 22 } },
    {
      timestamp: 24,17.50,
      type: 'song',
      data: { artist: 'Becky G', title: "Shower" },
    },
    { timestamp: 24,54.00, type: 'song', data: { artist: '???', title: '???' } },
    { timestamp: 24,53.00, type: 'horn', data: { counter: 23 } },
    { timestamp: 25,09.00, type: 'song', data: { artist: '???', title: '???' } },
    { timestamp: 25,23.00, type: 'horn', data: { counter: 24 } },
    { timestamp: 25,24.00, type: 'song', data: { artist: 'FISHER vs Famke Louise', title: 'Losing it / VROOM' } },
    { timestamp: 26,23.00, type: 'horn', data: { counter: 25 } },
    { timestamp: 26,24.50, type: 'song', data: { artist: 'Wamdue Project', title: 'King Of My Castle' } },
    { timestamp: 26,53.00, type: 'horn', data: { counter: 26 } },
    {
      timestamp: 26,55.00,
      type: 'song',
      data: { artist: 'Eric Prydz', title: 'Pjanoo' },
    },
    { timestamp: 27,20.00, type: 'song', data: { artist: 'Avicii, Sebastien Drums', title: 'My Feelings For You' } },
    { timestamp: 27,47.00, type: 'horn', data: { counter: 27 } },
    {
      timestamp: 28,02.00,
      type: 'song',
      data: { artist: 'Pitbull, TJR', title: 'Don't stop the party' },
    },
    {
      timestamp: 28,33.00,
      type: 'song',
      data: { artist: '???', title: '???' },
    },
    { timestamp: 29,02.50, type: 'song', data: { artist: 'The Bad Touch', title: 'Discovery Channel' } },
    { timestamp: 29,15.50, type: 'horn', data: { counter: 28 } },
    { timestamp: 29,47.30, type: 'horn', data: { counter: 29 } },
    { timestamp: 29,48.00, type: 'song', data: { artist: 'Snollebollekes', title: 'Snollebollekes' } },
    { timestamp: 30,34.00, type: 'horn', data: { counter: 30 } },
    { timestamp: 30,34.00, type: 'song', data: { artist: 'Evert Baptist', title: 'La La La Gehaktbal' } },
    { timestamp: 31,35.00, type: 'song', data: { artist: 'Gebroeders Rossig', title: 'Links, Rechts, Voor, Terug' } },
    { timestamp: 31,37.00, type: 'horn', data: { counter: 31 } },
    { timestamp: 32,04.00, type: 'song', data: { artist: '???', title: 'Ali Express' } },
    { timestamp: 32,26.00, type: 'horn', data: { counter: 32 } },
    { timestamp: 32,26.00, type: 'song', data: { artist: 'Gebroeders Rossig', title: 'Hallo Allemaal' } },
    { timestamp: 32,56.50, type: 'song', data: { artist: '???', title: '???' } },
    { timestamp: 33,00.00, type: 'horn', data: { counter: 33 } },
    { timestamp: 32,30.00, type: 'song', data: { artist: 'Andre Hazes', title: 'Leef' } },
    { timestamp: 33,30.50, type: 'horn', data: { counter: 34 } },
    {
      timestamp: 34,00.00,
      type: 'song',
      data: { artist: 'Zware Jongens', title: 'De Kneu' },
    },
    { timestamp: 34,31.70, type: 'horn', data: { counter: 35 } },
    { timestamp: 34,32.00, type: 'song', data: { artist: '???', title: '???' } },
    { timestamp: 35,09.00, type: 'song', data: { artist: '???', title: '???' } },
    { timestamp: 35,24.30, type: 'horn', data: { counter: 36 } },
    { timestamp: 35,54.00, type: 'horn', data: { counter: 37 } },
    { timestamp: 35,55.00, type: 'song', data: { artist: 'Dua Lipa', title: 'One Kiss' }, },
    { timestamp: 36,39.50, type: 'song', data: { artist: 'Party Squad', title: 'Ik ga hard' }, },
    { timestamp: 36,55.00, type: 'song', data: { artist: 'Epic Sax Guy', title: 'Epic Sax Guy' }, },
    { timestamp: 37,07.50, type: 'horn', data: { counter: 38 } },
    {
      timestamp: 37,09.00,
      type: 'song',
      data: { artist: 'Helene Fischer', title: 'Atemlos durch die Nacht' },
    },
    {
      timestamp: 37,57.00,
      type: 'song',
      data: { artist: 'Flo Rida, Sia', title: 'Wild Ones' },
    },
    { timestamp: 38,25.00, type: 'horn', data: { counter: 39 } },
    { timestamp: 38,26.00, type: 'song', data: { artist: '???', title: '???' } },
    { timestamp: 38,55.00, type: 'song', data: { artist: '???', title: '???' } },
    { timestamp: 39,29.00, type: 'song', data: { artist: 'The Proclaimers', title: "I'm Gonna Be (500 Miles)" } },
    { timestamp: 2431.20, type: 'horn', data: { counter: 40 } },
    { timestamp: 2460.00, type: 'song', data: { artist: 'Die Atzen', title: 'Disco Pogo' } },
    { timestamp: 2488.60, type: 'horn', data: { counter: 41 } },
    { timestamp: 2534.00, type: 'song', data: { artist: 'Lorenz Büffel', title: 'Johnny Däpp' } },
    { timestamp: 2554.90, type: 'horn', data: { counter: 42 } },
    { timestamp: 2587.00, type: 'song', data: { artist: 'Zware Jongens', title: 'Jodeljump' } },
    { timestamp: 2606.35, type: 'horn', data: { counter: 43 } },
    { timestamp: 2635.00, type: 'song', data: { artist: 'Parla & Pardoux', title: 'Liberté' } },
    { timestamp: 2663.46, type: 'horn', data: { counter: 44 } },
    { timestamp: 2695.00, type: 'song', data: { artist: 'Markus Becker', title: 'Das rote Pferd' } },
    { timestamp: 2729.00, type: 'horn', data: { counter: 45 } },
    { timestamp: 2743.00, type: 'song', data: { artist: 'Olaf Henning', title: 'Cowboy und Indianer' } },
    { timestamp: 2783.30, type: 'horn', data: { counter: 46 } },
    { timestamp: 2785.00, type: 'song', data: { artist: 'Ch!pz', title: 'Cowboy' } },
    { timestamp: 2824.00, type: 'song', data: { artist: 'Toy-Box', title: 'Tarzan & Jane' } },
    { timestamp: 2849.40, type: 'horn', data: { counter: 47 } },
    { timestamp: 2879.00, type: 'song', data: { artist: 'Toy-Box', title: 'Sailor Song' } },
    { timestamp: 2919.00, type: 'horn', data: { counter: 48 } },
    { timestamp: 2922.00, type: 'song', data: { artist: 'Vengaboys', title: 'Boom, Boom, Boom, Boom!!' } },
    { timestamp: 2974.58, type: 'horn', data: { counter: 49 } },
    { timestamp: 2998.00, type: 'song', data: { artist: 'Vengaboys', title: 'To Brazil!' } },
    { timestamp: 3038.76, type: 'horn', data: { counter: 50 } },
    { timestamp: 3070.00, type: 'song', data: { artist: 'Snollebollekes', title: 'Bam bam (bam)' } },
    { timestamp: 3103.18, type: 'horn', data: { counter: 51 } },
    { timestamp: 3120.00, type: 'song', data: { artist: 'Def Rhymz', title: 'Schudden' } },
    { timestamp: 3160.16, type: 'horn', data: { counter: 52 } },
    { timestamp: 3190.00, type: 'song', data: { artist: 'Cooldown Café', title: 'Hey baby' } },
    { timestamp: 3214.80, type: 'horn', data: { counter: 53 } },
    {
      timestamp: 3232.00,
      type: 'song',
      data: { artist: 'Gebroeders Ko', title: 'Schatje, mag ik je foto' },
    },
    { timestamp: 3278.55, type: 'horn', data: { counter: 54 } },
    { timestamp: 3279.00, type: 'song', data: { artist: 'Guus Meeuwis', title: 'Het is een nacht' } },
    { timestamp: 3340.80, type: 'horn', data: { counter: 55 } },
    { timestamp: 3356.00, type: 'song', data: { artist: 'Tom Waes', title: 'Dos cervezas' } },
    { timestamp: 3398.04, type: 'horn', data: { counter: 56 } },
    { timestamp: 3412.00, type: 'song', data: { artist: 'Peter Wackel', title: 'Vollgas' } },
    { timestamp: 3439.00, type: 'song', data: { artist: 'Peter Wackel', title: 'Scheiß drauf!' } },
    { timestamp: 3464.95, type: 'horn', data: { counter: 57 } },
    {
      timestamp: 3467.00,
      type: 'song',
      data: { artist: 'Ikke Hüftgold', title: 'Dicke titten, kartoffelsalat' },
    },
    { timestamp: 3519.75, type: 'horn', data: { counter: 58 } },
    {
      timestamp: 3521.00,
      type: 'song',
      data: { artist: 'Tim Toupet', title: 'Fliegerlied (So ein schöner Tag)' },
    },
    { timestamp: 3564.00, type: 'song', data: { artist: 'Cooldown Café', title: "Met z'n allen" } },
    { timestamp: 3576.36, type: 'horn', data: { counter: 59 } },
    { timestamp: 3642.86, type: 'horn', data: { counter: 60 } },
    {
      timestamp: 3659.00,
      type: 'song',
      data: { artist: 'The Partysquad feat. Jayh, Sjaak & Reverse', title: 'Helemaal naar de klote' },
    },
    { timestamp: 3687.00, type: 'song', data: { artist: 'K-Liber', title: 'Viben' } },
    { timestamp: 3699.38, type: 'horn', data: { counter: 61 } },
    { timestamp: 3752.85, type: 'horn', data: { counter: 62 } },
    {
      timestamp: 3755.00,
      type: 'song',
      data: { artist: 'FeestDJRuud & Dirtcaps feat. Sjaak & Kraantje Pappie', title: 'Weekend' },
    },
    { timestamp: 3807.60, type: 'horn', data: { counter: 63 } },
    { timestamp: 3808.00, type: 'song', data: { artist: 'Lawineboys', title: 'Joost' } },
    {
      timestamp: 3860.00,
      type: 'song',
      data: { artist: 'Gebroeders Ko', title: 'Ik heb een toeter op mijn waterscooter' },
    },
    { timestamp: 3873.60, type: 'horn', data: { counter: 64 } },
    { timestamp: 3904.00, type: 'song', data: { artist: 'Gebroeders Ko', title: 'Tringeling' } },
    { timestamp: 3931.55, type: 'horn', data: { counter: 65 } },
    { timestamp: 3975.00, type: 'song', data: { artist: 'Basshunter', title: 'Boten Anna' } },
    { timestamp: 3987.41, type: 'horn', data: { counter: 66 } },
    { timestamp: 4029.00, type: 'song', data: { artist: 'Lawineboys', title: 'Wat zullen we drinken' } },
    { timestamp: 4050.00, type: 'horn', data: { counter: 67 } },
    { timestamp: 4081.00, type: 'song', data: { artist: 'Lamme Frans', title: 'Wakker met een biertje!' } },
    { timestamp: 4112.80, type: 'horn', data: { counter: 68 } },
    {
      timestamp: 4124.18,
      type: 'song',
      data: { artist: 'Lawineboys feat. DJ Jerome', title: 'Seks met die kale' },
    },
    { timestamp: 4175.00, type: 'horn', data: { counter: 69 } },
    { timestamp: 4177.00, type: 'song', data: { artist: 'Zombie Nation', title: 'Kernkraft 400' } },
    { timestamp: 4227.53, type: 'horn', data: { counter: 70 } },
    { timestamp: 4230.00, type: 'song', data: { artist: 'DJ Boozywoozy', title: 'Party Affair' } },
    { timestamp: 4280.12, type: 'horn', data: { counter: 71 } },
    { timestamp: 4289.00, type: 'song', data: { artist: '2Unlimited', title: 'No Limit' } },
    { timestamp: 4340.73, type: 'horn', data: { counter: 72 } },
    { timestamp: 4343.00, type: 'song', data: { artist: 'DJ Kicken vs. MC-Q', title: "Ain't No Party" } },
    { timestamp: 4408.00, type: 'horn', data: { counter: 73 } },
    { timestamp: 4411.00, type: 'song', data: { artist: 'Jan Wayne', title: 'Becuase the Night' } },
    { timestamp: 4455.00, type: 'song', data: { artist: 'Cascada', title: 'Everytime We Touch' } },
    { timestamp: 4466.80, type: 'horn', data: { counter: 74 } },
    { timestamp: 4510.00, type: 'song', data: { artist: "Gigi D'Agostino", title: "L'amour toujours" } },
    { timestamp: 4520.84, type: 'horn', data: { counter: 75 } },
    { timestamp: 4573.00, type: 'song', data: { artist: 'Jason Paige', title: "Gotta Catch 'M All" } },
    { timestamp: 4578.00, type: 'horn', data: { counter: 76 } },
    { timestamp: 4636.00, type: 'song', data: { artist: 'Scooter', title: 'How Much Is The Fish' } },
    { timestamp: 4644.94, type: 'horn', data: { counter: 77 } },
    { timestamp: 4674.00, type: 'song', data: { artist: 'Scooter', title: 'Weekend' } },
    { timestamp: 4700.50, type: 'horn', data: { counter: 78 } },
    { timestamp: 4714.00, type: 'song', data: { artist: 'Scooter', title: 'One (Always Hardcore)' } },
    { timestamp: 4764.00, type: 'horn', data: { counter: 79 } },
    { timestamp: 4766.00, type: 'song', data: { artist: 'Scooter', title: 'Maria (I Like It Loud)' } },
    { timestamp: 4818.00, type: 'song', data: { artist: 'Scooter', title: "J'adore Hardcore" } },
    { timestamp: 4829.10, type: 'horn', data: { counter: 80 } },
    {
      timestamp: 4860.00,
      type: 'song',
      data: { artist: 'Wildstylez feat. Niels Geusebroek', title: 'Year of Summer' },
    },
    { timestamp: 4887.70, type: 'horn', data: { counter: 81 } },
    {
      timestamp: 4929.00,
      type: 'song',
      data: { artist: 'Brennan Heart & Wildstylez', title: 'Lose My Mind' },
    },
    { timestamp: 4952.43, type: 'horn', data: { counter: 82 } },
    { timestamp: 5004.50, type: 'horn', data: { counter: 83 } },
    { timestamp: 5006.00, type: 'song', data: { artist: 'Starkoo', title: 'Ik wil je' } },
    {
      timestamp: 5059.00,
      type: 'song',
      data: { artist: 'Feestteam', title: 'Let It Be / Hey Jude (mix)' },
    },
    { timestamp: 5070.43, type: 'horn', data: { counter: 84 } },
    { timestamp: 5124.46, type: 'horn', data: { counter: 85 } },
    {
      timestamp: 5179.00,
      type: 'song',
      data: { artist: 'DJ Nikolai & DJ Mike van Dijk', title: 'Piano Man' },
    },
    { timestamp: 5187.80, type: 'horn', data: { counter: 86 } },
    { timestamp: 5237.00, type: 'song', data: { artist: 'Robbie Williams', title: 'Angels' } },
    { timestamp: 5242.71, type: 'horn', data: { counter: 87 } },
    { timestamp: 5278.00, type: 'song', data: { artist: 'Enrique Iglesias', title: 'Hero' } },
    { timestamp: 5307.70, type: 'horn', data: { counter: 88 } },
    {
      timestamp: 5331.00,
      type: 'song',
      data: { artist: 'Whitney Houston', title: 'I Will Always Love You' },
    },
    { timestamp: 5373.80, type: 'horn', data: { counter: 89 } },
    {
      timestamp: 5380.00,
      type: 'song',
      data: { artist: 'Mariah Carey', title: 'All I Want For Christmas' },
    },
    { timestamp: 5431.74, type: 'horn', data: { counter: 90 } },
    {
      timestamp: 5444.00,
      type: 'song',
      data: { artist: 'Kraantje Pappie', title: 'Feesttent (FeestDJRuud remix)' },
    },
    { timestamp: 5487.80, type: 'horn', data: { counter: 91 } },
    { timestamp: 5490.25, type: 'song', data: { artist: 'New Kids feat. DJ Paul Elstak', title: 'Turbo' } },
    { timestamp: 5555.55, type: 'horn', data: { counter: 92 } },
    { timestamp: 5558.00, type: 'song', data: { artist: 'Lipstick', title: "I'm a Raver" } },
    { timestamp: 5591.00, type: 'song', data: { artist: 'Nakatomi', title: 'Children of the Night' } },
    { timestamp: 5612.00, type: 'horn', data: { counter: 93 } },
    {
      timestamp: 5614.00,
      type: 'song',
      data: { artist: 'Charly Lownoise & Mental Theo', title: 'Wonderful Days' },
    },
    { timestamp: 5659.00, type: 'song', data: { artist: 'DJ Paul Elstak', title: 'Luv You More' } },
    { timestamp: 5667.15, type: 'horn', data: { counter: 94 } },
    { timestamp: 5704.00, type: 'song', data: { artist: 'DJ Paul Elstak', title: 'Rainbow In The Sky' } },
    { timestamp: 5730.65, type: 'horn', data: { counter: 95 } },
    {
      timestamp: 5733.00,
      type: 'song',
      data: { artist: 'Evil Activities', title: 'Nobody Said It Was Easy' },
    },
    { timestamp: 5782.90, type: 'horn', data: { counter: 96 } },
    { timestamp: 5827.00, type: 'song', data: { artist: 'Melrose', title: 'O' } },
    { timestamp: 5846.32, type: 'horn', data: { counter: 97 } },
    { timestamp: 5855.00, type: 'song', data: { artist: 'Backstreet Boys', title: 'I Want It That Way' } },
    { timestamp: 5902.03, type: 'horn', data: { counter: 98 } },
    { timestamp: 5933.00, type: 'song', data: { artist: 'R. Kelly', title: "The World's Greatest" } },
    { timestamp: 5969.88, type: 'horn', data: { counter: 99 } },
    { timestamp: 5970.00, type: 'song', data: { artist: 'Céline Dion', title: 'My Heart Will Go On' } },
    { timestamp: 6020.00, type: 'horn', data: { counter: 100 } },
  ],
};

export default centurion;
