import MixTape from './mix-tape';

const centurion: MixTape = {
  name: 'Gebroeders Scooter - Totale EscalaTIEN',
  songFile: '/audio/gebroeders-scooter-escalatien.mp3',
  feed: [
    { timestamp: 10, type: 'horn', data: { counter: 0 } },
    { timestamp: 46.00, type: 'song', data: { artist: 'Vanessa Carlton', title: 'A Thousand Miles' } },
    { timestamp: 1,37.00, type: 'song', data: { artist: 'Snoop Dogg, Wiz Khalifa, Bruno Mars', title: 'Young Wild & Free' } },
    { timestamp: 1,58.00, type: 'song', data: { artist: 'The Game, 50 Cent', title: 'How We Do' } },
    { timestamp: 2,33.50, type: 'horn', data: { counter: 1 } },
    { timestamp: 2,34.00, type: 'song', data: { artist: 'Nelly & The Partysquad', title: 'Ride Wit Me & Non Stop' } },
    { timestamp: 3,32.00, type: 'song', data: { artist: 'Natasha Beddingfield', title: 'Unwritten' } },
    { timestamp: 3,51.00, type: 'horn', data: { counter: 2 } },
    { timestamp: 4,19.00, type: 'song', data: { artist: 'Gwen Stefani, Eve', title: 'Rich Girl' } },
    { timestamp: 5,00.00, type: 'song', data: { artist: 'Smashmouth', title: 'All Star' } },
    { timestamp: 5,37.00, type: 'horn', data: { counter: 3 } },
    { timestamp: 5,55.50, type: 'song', data: { artist: 'Daddy Yankee, Natti Natasha, Becky G, Bad Bunny', title: 'Dura' } },
    { timestamp: 6,27.00, type: 'horn', data: { counter: 4 } },
    { timestamp: 6,29.00, type: 'song', data: { artist: 'Bizzey, Jozo, Kraantje Pappie', title: 'Traag', } },
    { timestamp: 7,08.00, type: 'song', data: { artist: 'Bizzey, Kraantje Pappie, Chivv, Yung Felix', title: 'JA!' } },
    { timestamp: 7,27.00, type: 'song', data: { artist: 'Bizzey, Kraantje Pappie, Jonna Fraser, Ramiks', title: 'DRUP' } },
    { timestamp: 7,46.50, type: 'song', data: { artist: 'Ronnie Flex, Maan', title: 'Blijf Bij Mij' } },
    { timestamp: 8,05.50, type: 'song', data: { artist: 'Kelly Rowland, Nelly', title: 'Dilemma' } },
    { timestamp: 8,25.00, type: 'song', data: { artist: 'Justin Bieber', title: 'Sorry' } },
    { timestamp: 8,43.80, type: 'horn', data: { counter: 5 } },
    { timestamp: 9,03.00, type: 'song', data: { artist: 'Bruno Mars', title: 'Drippin in Finesse' } },
    { timestamp: 9,40.00, type: 'song', data: { artist: 'K3', title: '10.000 luchtballonnen' } },
    { timestamp: 10,31.00, type: 'horn', data: { counter: 6 } },
    { timestamp: 10,33.00, type: 'song', data: { artist: 'Scissor Sisters', title: "I don't feel like dancing" } },
    { timestamp: 11,36.00, type: 'song', data: { artist: 'Robbie Williams', title: 'Rock DJ' } },
    { timestamp: 11,52.30, type: 'horn', data: { counter: 7 } },
    { timestamp: 12,21.50, type: 'song', data: { artist: 'Shantel', title: 'Disko Partizani' } },
    { timestamp: 12.39.00, type: 'horn', data: { counter: 8 } },
    { timestamp: 12,57.50, type: 'song', data: { artist: 'Rebecca Black', title: 'Friday' } },
    { timestamp: 13,12.00, type: 'horn', data: { counter: 9 } },
    { timestamp: 13,40.00, type: 'horn', data: { counter: 10 } },
    { timestamp: 13,40.00, type: 'song', data: { artist: 'JIVEjones', title: 'Me, Myself & I', } },
    { timestamp: 14,13.00, type: 'song', data: { artist: 'Vanilla Ice', title: 'Ice Ice Baby' } },
    { timestamp: 14,30.00, type: 'song', data: { artist: 'MC Miker G, DJ Sven', title: 'Holiday Rap' } },
    { timestamp: 15,01.00, type: 'horn', data: { counter: 11 } },
    { timestamp: 15,02.00, type: 'song', data: { artist: 'Kees Diks', title: 'Het Barbecue Lied' } },
    { timestamp: 15,49.10, type: 'horn', data: { counter: 12 } },
    { timestamp: 15,51.00, type: 'song', data: { artist: 'De Jeugd van Tegenwoordig', title: 'Get Spanish' } },
    { timestamp: 16,37.00, type: 'horn', data: { counter: 13 } },
    { timestamp: 16,38.00, type: 'song', data: { artist: 'Sjaak', title: 'Stap voor stap' } },
    { timestamp: 17,23.80, type: 'horn', data: { counter: 14 } },
    { timestamp: 17,25.00, type: 'song', data: { artist: 'Jairzinho, Sven Alias, BKO, Boef', title: 'Tempo' } },
    { timestamp: 17,43.00, type: 'song', data: { artist: 'Spacekees, Terilekst, Jiggy Djé', title: 'Ik Wil Een Meisje' } },
    { timestamp: 18.13.00, type: 'song', data: { artist: 'Discodip', title: "Meisjes met IJsjes" } },
    { timestamp: 18,57.50, type: 'horn', data: { counter: 15 } },
    { timestamp: 18,59.00, type: 'song', data: { artist: 'MEROL', title: 'LEKKER MET DE MEIDEN/MANNEN' } },
    { timestamp: 19,45.70, type: 'horn', data: { counter: 16 } },
    { timestamp: 19,46.00, type: 'song', data: { artist: 'Twenty 4 Seven', title: 'Slave To The Music' } },
    { timestamp: 20,16.00, type: 'song', data: { artist: 'David Hasselhoff', title: 'Looking for Freedom' } },
    { timestamp: 20,16.00, type: 'horn', data: { counter: 17 } },
    { timestamp: 20,46.00, type: 'song', data: { artist: 'Boney M.', title: 'Rivers of Babylon' } },
    { timestamp: 21,17.41, type: 'horn', data: { counter: 18 } },
    { timestamp: 21,17.00, type: 'song', data: { artist: 'Gwen Stefani, Akon', title: 'The Sweet Escape' } },
    { timestamp: 21,54.50, type: 'song', data: { artist: 'Pink', title: 'So What' } },
    { timestamp: 22,06.00, type: 'horn', data: { counter: 19 } },
    { timestamp: 22,36.00, type: 'song', data: { artist: 'Jessie J', title: 'Domino' } },
    { timestamp: 23,06.30, type: 'horn', data: { counter: 20 } },
    { timestamp: 23,06.30, type: 'song', data: { artist: 'Katy Perry', title: 'Teenage Dream' } },
    { timestamp: 23,34.30, type: 'horn', data: { counter: 21 } },
    { timestamp: 23,36.00, type: 'song', data: { artist: 'Bon Jovi', title: "Livin' on a Prayer" } },
    { timestamp: 23,55.40, type: 'horn', data: { counter: 22 } },
    { timestamp: 24,17.50, type: 'song', data: { artist: 'Becky G', title: "Shower" } },
    { timestamp: 24,54.00, type: 'song', data: { artist: 'Missy Elliott, Ciara, Fat Man Scoop', title: 'Lose Control' } },
    { timestamp: 24,53.00, type: 'horn', data: { counter: 23 } },
    { timestamp: 25,23.00, type: 'horn', data: { counter: 24 } },
    { timestamp: 25,24.00, type: 'song', data: [{ artist: 'FISHER', title: 'Losing it' }, { artist: 'Famke Louise, Bokoesam', title: 'VROOM' }] },
    { timestamp: 26,23.00, type: 'horn', data: { counter: 25 } },
    { timestamp: 26,24.50, type: 'song', data: { artist: 'Wamdue Project', title: 'King Of My Castle' } },
    { timestamp: 26,53.00, type: 'horn', data: { counter: 26 } },
    { timestamp: 26,55.00, type: 'song', data: { artist: 'Eric Prydz', title: 'Pjanoo' } },
    { timestamp: 27,20.00, type: 'song', data: { artist: 'Avicii, Sebastien Drums', title: 'My Feelings For You' } },
    { timestamp: 27,47.00, type: 'horn', data: { counter: 27 } },
    { timestamp: 28,02.00, type: 'song', data: { artist: 'Pitbull, TJR', title: "Don't stop the party" } },
    { timestamp: 28,33.00, type: 'song', data: { artist: 'The Outhere Brothers', title: 'Boom Boom Boom' } },
    { timestamp: 29,02.50, type: 'song', data: { artist: 'The Bad Touch', title: 'Discovery Channel' } },
    { timestamp: 29,15.50, type: 'horn', data: { counter: 28 } },
    { timestamp: 29,47.30, type: 'horn', data: { counter: 29 } },
    { timestamp: 29,48.00, type: 'song', data: { artist: 'Snollebollekes', title: 'Snollebollekes' } },
    { timestamp: 30,34.00, type: 'horn', data: { counter: 30 } },
    { timestamp: 30,34.00, type: 'song', data: { artist: 'Evert Baptist', title: 'La La La Gehaktbal' } },
    { timestamp: 31,35.00, type: 'song', data: { artist: 'Gebroeders Rossig', title: 'Links, Rechts, Voor, Terug' } },
    { timestamp: 31,37.00, type: 'horn', data: { counter: 31 } },
    { timestamp: 32,04.00, type: 'song', data: { artist: 'Gebroeders Rossig', title: 'Alie Exprezz' } },
    { timestamp: 32,26.00, type: 'horn', data: { counter: 32 } },
    { timestamp: 32,26.00, type: 'song', data: { artist: 'Gebroeders Rossig', title: 'Hallo Allemaal' } },
    { timestamp: 32,56.50, type: 'song', data: { artist: 'John de Bever', title: 'Jij Krijgt Die Lach Niet Van Mijn Gezicht' } },
    { timestamp: 33,00.00, type: 'horn', data: { counter: 33 } },
    { timestamp: 32,30.00, type: 'song', data: { artist: 'Andre Hazes', title: 'Leef' } },
    { timestamp: 33,30.50, type: 'horn', data: { counter: 34 } },
    { timestamp: 34,00.00, type: 'song', data: { artist: 'Zware Jongens', title: 'De Kneu' } },
    { timestamp: 34,31.70, type: 'horn', data: { counter: 35 } },
    { timestamp: 34,32.00, type: 'song', data: { artist: 'Camila Cabello, Young Thug', title: 'Havana' } },
    { timestamp: 35,09.00, type: 'song', data: { artist: '???', title: '???' } },
    { timestamp: 35,24.30, type: 'horn', data: { counter: 36 } },
    { timestamp: 35,54.00, type: 'horn', data: { counter: 37 } },
    { timestamp: 35,55.00, type: 'song', data: { artist: 'Calvin Harris, Dua Lipa', title: 'One Kiss' }, },
    { timestamp: 36,39.50, type: 'song', data: { artist: 'Party Squad', title: 'Ik ga hard' }, },
    { timestamp: 36,55.00, type: 'song', data: { artist: 'Epic Sax Guy', title: 'Epic Sax Guy' }, },
    { timestamp: 37,07.50, type: 'horn', data: { counter: 38 } },
    { timestamp: 37,09.00, type: 'song', data: { artist: 'Helene Fischer', title: 'Atemlos durch die Nacht' } },
    { timestamp: 37,57.00, type: 'song', data: { artist: 'Flo Rida, Sia', title: 'Wild Ones' } },
    { timestamp: 38,25.00, type: 'horn', data: { counter: 39 } },
    { timestamp: 38,26.00, type: 'song', data: { artist: 'Michael Mind', title: 'Gotta Let You Go' } },
    { timestamp: 38,55.00, type: 'song', data: { artist: 'Bob Sinclar, Gary Pine', title: 'Sound of Freedom' } },
    { timestamp: 39,29.00, type: 'song', data: { artist: 'The Proclaimers', title: "I'm Gonna Be (500 Miles)" } },
    { timestamp: 39,44.60, type: 'horn', data: { counter: 40 } },
    { timestamp: 2460.00, type: 'song', data: { artist: 'Beastie Boys', title: 'Fight For Your Right' } },
    { timestamp: 40,29.00, type: 'horn', data: { counter: 41 } },
    { timestamp: 40,31.50, type: 'horn', data: { counter: 41 } },
    { timestamp: 40,50.80, type: 'song', data: { artist: 'Nirvana', title: 'Smells Like Teen Spirit' } },
    { timestamp: 40,58.30, type: 'horn', data: { counter: 42 } },
    { timestamp: 41,37.50, type: 'horn', data: { counter: 43 } },
    { timestamp: 41,41.00, type: 'horn', data: { counter: 44 } },
    { timestamp: 41,44.00, type: 'song', data: { artist: 'Gerard Joling', title: 'Zing met me mee' } },
    { timestamp: 41,24.00, type: 'song', data: { artist: 'Paul de Laat', title: 'Meer of Minder' } },
    { timestamp: 42,49.00, type: 'horn', data: { counter: 45 } },
    { timestamp: 43,01.00, type: 'horn', data: { counter: 46 } },
    { timestamp: 43,02.00, type: 'song', data: { artist: 'DJ Birdy', title: 'Bird Dance' } },
    { timestamp: 43,30.00, type: 'song', data: { artist: 'Snollebollekes, Gerard Joling', title: 'Total Loss' } },
    { timestamp: 43,57.80, type: 'horn', data: { counter: 47 } },
    { timestamp: 44,20.00, type: 'song', data: { artist: 'Batiste', title: 'Vakantieliefde' } },
    { timestamp: 44,49.50, type: 'horn', data: { counter: 48 } },
    { timestamp: 45,16.00, type: 'song', data: { artist: 'Meat Loaf, Ellen Foley', title: 'Paradise By the Dashboard Light' } },
    { timestamp: 45,38.40, type: 'horn', data: { counter: 49 } },
    { timestamp: 46,01.00, type: 'horn', data: { counter: 50 } },
    { timestamp: 46,01.00, type: 'song', data: { artist: 'David Guetta, Martin Garrix, Brooks', title: 'Like I do' } },
    { timestamp: 46,29.00, type: 'song', data: { artist: 'Avicii, Sandro Cavazza', title: 'Without You' } },
    { timestamp: 46,44.00, type: 'horn', data: { counter: 51 } },
    { timestamp: 47,10.90, type: 'horn', data: { counter: 52 } },
    { timestamp: 47,11.00, type: 'song', data: { artist: 'Martin Garrix, Bonn', title: 'High On Life' } },
    { timestamp: 47,26.80, type: 'horn', data: { counter: 53 } },
    { timestamp: 47,55.00, type: 'song', data: [{ artist: 'Armin van Buuren', title: 'Blah Blah Blah' }, { artist: 'Zany', title: 'Vreet Spirit' }] },
    { timestamp: 48,28.30, type: 'horn', data: { counter: 54 } },
    { timestamp: 48,58.00, type: 'song', data: { artist: 'SRV Mannen', title: 'Bier en... (de essentie van Carnaval)' } },
    { timestamp: 48,59.20, type: 'horn', data: { counter: 55 } },
    { timestamp: 49,28.50, type: 'song', data: { artist: 'PartyfrieX, Schorre Chef & MC Vals', title: 'Ik moet zuipen!' } },
    { timestamp: 49,56.00, type: 'horn', data: { counter: 56 } },
    { timestamp: 50,24.50, type: 'song', data: { artist: 'Peter Koelewijn', title: 'Kom Van Dat Dak Af' } },
    { timestamp: 50,42.80, type: 'horn', data: { counter: 57 } },
    { timestamp: 50,43.50, type: 'song', data: { artist: 'Stefan en Sean, Bram Krikke', title: 'Potentie' } },
    { timestamp: 50,58.00, type: 'horn', data: { counter: 58 } },
    { timestamp: 51,24.30, type: 'horn', data: { counter: 59 } },
    { timestamp: 51,50.00, type: 'song', data: { artist: '2 Brothers Unlimited', title: 'Penis Dance' } },
    { timestamp: 52,03.50, type: 'horn', data: { counter: 60 } },
    { timestamp: 52,29.00, type: 'song', data: { artist: 'DJ Khaled, T-Pain, Ludacris, Snoop Dogg', title: "All I Do Is Win" } },
    { timestamp: 52,35.90, type: 'horn', data: { counter: 61 } },
    { timestamp: 52,04.00, type: 'song', data: { artist: 'Jebroer, Jayh, Skinto, Stepherd', title: 'Benaan - (Bigger Better Anthem)' } },
    { timestamp: 53,14.00, type: 'horn', data: { counter: 62 } },
    { timestamp: 53,27.00, type: 'song', data: { artist: 'Snollebollekes, Coen & Sander', title: 'Feest Waarvan Ik Morgen Niks Meer Weet' } },
    { timestamp: 53,55.00, type: 'horn', data: { counter: 63 } },
    { timestamp: 54,07.70, type: 'song', data: { artist: 'Buren Van De Brandweer', title: 'Pilsies Voor De Vat' } },
    { timestamp: 54,32.50, type: 'horn', data: { counter: 64 } },
    { timestamp: 54,57.00, type: 'song', data: { artist: 'Da Tweekaz', title: 'Jägermeister' } },
    { timestamp: 55,33.90, type: 'horn', data: { counter: 65 } },
    { timestamp: 55,58.00, type: 'song', data: { artist: 'Pat B', title: 'Darth Raver' } },
    { timestamp: 56,22.00, type: 'horn', data: { counter: 66 } },
    { timestamp: 56,46.00, type: 'song', data: { artist: 'Jebroer, Paul Elstak, Pr Phunk', title: 'Engeltje' } },
    { timestamp: 57,12.30, type: 'horn', data: { counter: 67 } },
    { timestamp: 57,36.00, type: 'song', data: { artist: 'Jebroer, Outsiders', title: 'Flitsmeister' } },
    { timestamp: 57,47.00, type: 'horn', data: { counter: 68 } },
    { timestamp: 58,11.00, type: 'song', data: { artist: 'De Mosselman', title: 'Opzij' } },
    { timestamp: 58,34.50, type: 'song', data: { artist: 'Harris & Ford, Scooter', title: 'God Save The Rave' } },
    { timestamp: 58,46.00, type: 'horn', data: { counter: 69 } },
    { timestamp: 59,23.00, type: 'song', data: { artist: 'Marco Borsato', title: 'Ik Leef Niet Meer Voor Jou' } },
    { timestamp: 59,35.00, type: 'horn', data: { counter: 70 } },
    { timestamp: 60,23.80, type: 'horn', data: { counter: 71 } },
  ],
};

export default centurion;
